apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: covid19-countries
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: covid19-countries
    spec:
      containers:
        - image: "josephnp732/covid19_countries:v1"
          imagePullPolicy: Always
          name: covid19-countries
          ports:
            - containerPort: 3002