apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: covid19-all
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: covid19-all
    spec:
      containers:
        - image: "josephnp732/covid19_all:v1.1"
          imagePullPolicy: Always
          name: covid19-all
          ports:
            - containerPort: 3001